# Generated by Django 3.1.3 on 2021-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210326_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='business_email',
            field=models.EmailField(default='example@email.com', max_length=255),
        ),
    ]
