# Generated by Django 3.1.3 on 2021-04-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_business_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='business_email',
        ),
    ]
