# Generated by Django 3.1.3 on 2021-04-17 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0009_tenant_business_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0003_auto_20210403_1324'),
        ('company', '0009_auto_20210326_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=500)),
                ('detail', models.TextField(blank=True, max_length=3000, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('cleared', 'cleared')], default='pending', max_length=200, null=True)),
                ('type', models.CharField(choices=[('onetime', 'onetime'), ('re-occuring', 're-occuring')], default='onetime', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('custom_data', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='company.company')),
                ('contact', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='contact.contact')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdtransactions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tenant.tenant')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedtransactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
