# Generated by Django 3.1.3 on 2021-04-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.BigIntegerField(blank=True, default=0.0, null=True),
        ),
    ]
