# Generated by Django 3.1.3 on 2021-04-21 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0003_auto_20210403_1324'),
        ('tenant', '0009_tenant_business_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('link', models.URLField()),
                ('due_date', models.DateTimeField()),
                ('invoice_number', models.IntegerField()),
                ('invoice_header', models.CharField(blank=True, max_length=500, null=True)),
                ('issued_date', models.DateField()),
                ('extra_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('items', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('cleared', 'cleared'), ('canceled', 'canceled')], max_length=500)),
                ('is_drafted', models.BooleanField(default=0)),
                ('sub_total', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactinvoices', to='contact.contact')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdinvoice', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenantinvoices', to='tenant.tenant')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedinvoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
