# Generated by Django 3.1.3 on 2021-04-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210421_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
