# Generated by Django 3.1 on 2021-10-22 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicetemplate', '0005_auto_20210418_2001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0009_tenant_business_email'),
        ('contact', '0003_auto_20210403_1324'),
        ('invoice', '0003_auto_20210421_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicetemplate', to='invoicetemplate.invoicetemplate'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactinvoices', to='contact.contact'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdinvoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_drafted',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenantinvoices', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedinvoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
