# Generated by Django 3.1 on 2021-10-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20211022_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_header',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(),
        ),
    ]
