# Generated by Django 3.1.3 on 2021-04-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_auto_20210326_1717'),
        ('type', '0002_auto_20210325_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='tenant.tenant'),
        ),
    ]
