# Generated by Django 3.1 on 2021-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20211022_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
