# Generated by Django 3.1.3 on 2021-03-26 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0008_auto_20210326_1717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_of_ceo', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('emails', models.CharField(blank=True, help_text='enter comma separated email address', max_length=1000, null=True)),
                ('phone_numbers', models.CharField(blank=True, help_text='enter comma separated phone numbers address', max_length=1000, null=True)),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('region', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('industry', models.CharField(blank=True, max_length=500, null=True)),
                ('social_accounts', models.JSONField(blank=True, max_length=1000, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('created_by', models.ForeignKey(blank=True, default='unknown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreatedcompany', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, default='unknown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='tenant.tenant')),
                ('updated_by', models.ForeignKey(blank=True, default='unknown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userupdatedbycompany', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
