# Generated by Django 3.1.3 on 2021-03-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210326_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='emails',
            field=models.JSONField(blank=True, help_text='enter comma separated email address', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_numbers',
            field=models.CharField(blank=True, help_text='enter comma separated phone numbers address', max_length=1000, null=True),
        ),
    ]
