# Generated by Django 3.1.3 on 2021-03-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20210326_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_numbers',
            field=models.JSONField(default=list),
        ),
    ]
