# Generated by Django 3.1.3 on 2021-04-03 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0009_auto_20210326_2136'),
        ('tenant', '0008_auto_20210326_1717'),
        ('type', '0002_auto_20210325_1551'),
        ('contact', '0002_auto_20210326_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='client_position',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userassignedcontacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='company.company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreatedcontacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='emails',
            field=models.CharField(help_text='enter comma separated email address', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='type.type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userupdatedcontacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
