# Generated by Django 3.1.3 on 2021-04-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicetemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetemplate',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
