# Generated by Django 3.1.3 on 2021-04-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicetemplate', '0004_auto_20210418_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetemplate',
            name='name',
            field=models.CharField(default='puritan', max_length=500),
        ),
    ]
