# Generated by Django 3.1.3 on 2020-11-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of category', max_length=100, unique=True)),
                ('banner', models.FileField(blank=True, null=True, upload_to='banner/')),
            ],
            options={
                'verbose_name_plural': 'Tenant',
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
    ]
