# Generated by Django 3.1.3 on 2021-03-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20210326_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='modules',
            field=models.CharField(blank=True, default='CRM', help_text='Select modules you want to use', max_length=1000, null=True),
        ),
    ]
