# Generated by Django 3.1.3 on 2021-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_auto_20210326_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='number_of_staffs',
            field=models.PositiveBigIntegerField(blank=True, default=0, help_text='Enter name address', null=True),
        ),
    ]
